
#############################################
#Code for - Which vendors have the most trips, and what is the total revenue generated by that vendor?
#############################################

#Importing all libraries required for map reduce job
from mrjob.job import MRJob
from mrjob.step import MRStep

#defining class
class MRVendorCount(MRJob):

    #mapper for mapping key value pair
    def mapper(self, _, line):
        rec = line.split(",") #getting the record
        #Get the values for vendor and total amount which is conidered for revenue
        VendorID = rec[0] 
        TotAmt = rec[16]

        #Excluding the header row
        if TotAmt != 'total_amount':
            if VendorID == "1":
                Vendor = 'Creative Mobile Technologies'
            else:
                Vendor = 'VeriFone Inc.'
            yield (Vendor,float( TotAmt)) #Total Revenue
    
    #reducer which gets total revenue for each vendor    
    def reducer(self, key, values):
        yield key, sum(values)

#main function
if __name__ == '__main__':
    MRVendorCount.run()
