
#############################################
#Code for - Which vendors have the most trips, and what is the total revenue generated by that vendor?
#############################################

#Importing all libraries required for map reduce job
from mrjob.job import MRJob
from mrjob.step import MRStep

#defining class
class MRVendorCount(MRJob):
    #Defining steps for mapper reducer and for finding max after reducer runs
    def steps(self):
        return [
            MRStep(
                mapper = self.mapper,
                reducer = self.reducer,
            )
            ,
            MRStep(
                reducer = self.reducer_find_max
            )
        ]

    #mapper for mapping key value pair
    def mapper(self, _, line):
        rec = line.split(",") #getting the record
        
        VendorID = rec[0] 
        TotAmt = rec[16]
        
        #Excluding the header row
        if TotAmt != 'total_amount':
            if VendorID == "1":
                Vendor = 'Creative Mobile Technologies'
            else:
                Vendor = 'VeriFone Inc.'
            yield (Vendor, 1)
            
    #reducer provides count of vendors
    def reducer(self, key, values):  
        yield None, (sum(values),key)

    #This function to find which vendor count is more.
    def reducer_find_max(self, _,vendor_pair):
        yield max(vendor_pair)

#main function
if __name__ == '__main__':
    MRVendorCount.run()
